<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class ProjectHeaderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $now = Carbon::now();

    DB::table('project_header')->insert([
        [
            'project_code'    => 'PRJ-001',
            'project_name'    => 'Sistem Absensi Web',
            'request_date'    => $now->subDays(12),
            'requestor_id'    => 1,
            'dev_id'          => 2,
            'priority_id'     => 1,
            'status_id'       => 1,
            'description'     => 'Pembuatan sistem absensi berbasis web',
            'progress_date'   => $now->subDays(10),
            'progress_percent'=> 20,
            'start_date'      => '2025-09-01 08:00:00',
            'end_date'        => '2025-12-01 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-002',
            'project_name'    => 'Redesign UI Mobile App',
            'request_date'    => $now->subDays(15),
            'requestor_id'    => 3,
            'dev_id'          => 2,
            'priority_id'     => 2,
            'status_id'       => 2,
            'description'     => 'Redesign UI aplikasi mobile internal',
            'progress_date'   => $now->subDays(7),
            'progress_percent'=> 45,
            'start_date'      => '2025-08-10 08:00:00',
            'end_date'        => '2025-11-15 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-003',
            'project_name'    => 'Integrasi Payroll HRIS',
            'request_date'    => $now->subDays(8),
            'requestor_id'    => 2,
            'dev_id'          => 4,
            'priority_id'     => 3,
            'status_id'       => 3,
            'description'     => 'Integrasi sistem payroll dengan HRIS',
            'progress_date'   => $now->subDays(4),
            'progress_percent'=> 70,
            'start_date'      => '2025-07-01 08:00:00',
            'end_date'        => '2025-10-30 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-004',
            'project_name'    => 'Dashboard Penjualan',
            'request_date'    => $now->subDays(5),
            'requestor_id'    => 4,
            'dev_id'          => 1,
            'priority_id'     => 1,
            'status_id'       => 4,
            'description'     => 'Pembuatan dashboard monitoring penjualan',
            'progress_date'   => $now->subDays(2),
            'progress_percent'=> 90,
            'start_date'      => '2025-08-20 08:00:00',
            'end_date'        => '2025-10-20 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-005',
            'project_name'    => 'Otomatisasi Laporan Keuangan',
            'request_date'    => $now->subDays(3),
            'requestor_id'    => 5,
            'dev_id'          => 3,
            'priority_id'     => 2,
            'status_id'       => 1,
            'description'     => 'Otomatisasi laporan keuangan bulanan',
            'progress_date'   => $now->subDays(1),
            'progress_percent'=> 15,
            'start_date'      => '2025-10-01 08:00:00',
            'end_date'        => '2025-12-15 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-006',
            'project_name'    => 'Migrasi Database Server',
            'request_date'    => $now->subDays(9),
            'requestor_id'    => 6,
            'dev_id'          => 2,
            'priority_id'     => 3,
            'status_id'       => 2,
            'description'     => 'Migrasi database lama ke server baru',
            'progress_date'   => $now,
            'progress_percent'=> 40,
            'start_date'      => '2025-09-10 08:00:00',
            'end_date'        => '2025-11-30 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-007',
            'project_name'    => 'Notifikasi Otomatis Email',
            'request_date'    => $now->subDays(20),
            'requestor_id'    => 2,
            'dev_id'          => 5,
            'priority_id'     => 1,
            'status_id'       => 5,
            'description'     => 'Sistem notifikasi otomatis via email',
            'progress_date'   => $now,
            'progress_percent'=> 100,
            'start_date'      => '2025-07-01 08:00:00',
            'end_date'        => '2025-09-15 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-008',
            'project_name'    => 'Implementasi API HR Module',
            'request_date'    => $now->subDays(11),
            'requestor_id'    => 3,
            'dev_id'          => 1,
            'priority_id'     => 2,
            'status_id'       => 3,
            'description'     => 'Implementasi API internal untuk HR module',
            'progress_date'   => $now,
            'progress_percent'=> 60,
            'start_date'      => '2025-08-01 08:00:00',
            'end_date'        => '2025-10-25 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-009',
            'project_name'    => 'Sistem Ticketing Internal',
            'request_date'    => $now->subDays(14),
            'requestor_id'    => 4,
            'dev_id'          => 2,
            'priority_id'     => 1,
            'status_id'       => 4,
            'description'     => 'Pengembangan sistem ticketing internal',
            'progress_date'   => $now,
            'progress_percent'=> 80,
            'start_date'      => '2025-07-15 08:00:00',
            'end_date'        => '2025-10-10 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
        [
            'project_code'    => 'PRJ-010',
            'project_name'    => 'Portal Dokumentasi Internal',
            'request_date'    => $now->subDays(6),
            'requestor_id'    => 1,
            'dev_id'          => 3,
            'priority_id'     => 2,
            'status_id'       => 1,
            'description'     => 'Pembuatan portal dokumentasi internal',
            'progress_date'   => $now,
            'progress_percent'=> 10,
            'start_date'      => '2025-10-10 08:00:00',
            'end_date'        => '2026-01-20 17:00:00',
            'created_at'      => $now,
            'updated_at'      => $now,
        ],
    ]);
    }
}
