<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TicketsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tickets')->insert([
            [
                'ticket_code' => 'TCK-001',
                'user_id' => 1,
                'support_id' => 2,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 1,
                'priority_id' => 2,
                'problem' => 'Laptop tidak bisa menyala',
                'solution' => 'Ganti adaptor charger',
                'request_date' => Carbon::now()->subDays(10),
                'start_date' => Carbon::now()->subDays(9),
                'end_date' => Carbon::now()->subDays(8),
                'waiting_hour' => 2,
                'time_spent' => 90,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-002',
                'user_id' => 2,
                'support_id' => 3,
                'problem_category_id' => 1,
                'assets_id' => 2,
                'status_id' => 2,
                'priority_id' => 3,
                'problem' => 'Printer tidak terdeteksi di jaringan',
                'solution' => 'Reinstall driver dan konfigurasi IP printer',
                'request_date' => Carbon::now()->subDays(9),
                'start_date' => Carbon::now()->subDays(8),
                'end_date' => Carbon::now()->subDays(7),
                'waiting_hour' => 3,
                'time_spent' => 110,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-003',
                'user_id' => 3,
                'support_id' => 1,
                'problem_category_id' => 1,
                'assets_id' => 3,
                'status_id' => 3,
                'priority_id' => 1,
                'problem' => 'Sistem ERP tidak bisa login',
                'solution' => 'Reset session server',
                'request_date' => Carbon::now()->subDays(8),
                'start_date' => Carbon::now()->subDays(7),
                'end_date' => Carbon::now()->subDays(6),
                'waiting_hour' => 1,
                'time_spent' => 75,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-004',
                'user_id' => 1,
                'support_id' => 3,
                'problem_category_id' => 1,
                'assets_id' => 2,
                'status_id' => 1,
                'priority_id' => 2,
                'problem' => 'Email tidak bisa terkirim',
                'solution' => 'Cek konfigurasi SMTP dan clear cache',
                'request_date' => Carbon::now()->subDays(7),
                'start_date' => Carbon::now()->subDays(6),
                'end_date' => Carbon::now()->subDays(5),
                'waiting_hour' => 4,
                'time_spent' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-005',
                'user_id' => 2,
                'support_id' => 1,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 2,
                'priority_id' => 1,
                'problem' => 'Komputer sering restart sendiri',
                'solution' => 'Ganti PSU dan periksa RAM',
                'request_date' => Carbon::now()->subDays(6),
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->subDays(4),
                'waiting_hour' => 5,
                'time_spent' => 120,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-006',
                'user_id' => 3,
                'support_id' => 2,
                'problem_category_id' => 1,
                'assets_id' => 3,
                'status_id' => 3,
                'priority_id' => 3,
                'problem' => 'Aplikasi internal error 404',
                'solution' => 'Perbaiki routing dan deploy ulang',
                'request_date' => Carbon::now()->subDays(5),
                'start_date' => Carbon::now()->subDays(4),
                'end_date' => Carbon::now()->subDays(3),
                'waiting_hour' => 2,
                'time_spent' => 130,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-007',
                'user_id' => 1,
                'support_id' => 1,
                'problem_category_id' => 1,
                'assets_id' => 2,
                'status_id' => 2,
                'priority_id' => 2,
                'problem' => 'Monitor tidak menampilkan gambar',
                'solution' => 'Cek kabel HDMI dan ganti monitor',
                'request_date' => Carbon::now()->subDays(4),
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->subDays(2),
                'waiting_hour' => 1,
                'time_spent' => 60,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-008',
                'user_id' => 2,
                'support_id' => 3,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 1,
                'priority_id' => 1,
                'problem' => 'Access point tidak berfungsi',
                'solution' => 'Reset AP dan update firmware',
                'request_date' => Carbon::now()->subDays(3),
                'start_date' => Carbon::now()->subDays(2),
                'end_date' => Carbon::now()->subDay(),
                'waiting_hour' => 3,
                'time_spent' => 140,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-009',
                'user_id' => 3,
                'support_id' => 2,
                'problem_category_id' => 1,
                'assets_id' => 3,
                'status_id' => 2,
                'priority_id' => 3,
                'problem' => 'Keyboard tidak berfungsi',
                'solution' => 'Ganti keyboard baru dan test koneksi USB',
                'request_date' => Carbon::now()->subDays(2),
                'start_date' => Carbon::now()->subDay(),
                'end_date' => Carbon::now(),
                'waiting_hour' => 2,
                'time_spent' => 90,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-010',
                'user_id' => 1,
                'support_id' => 2,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 3,
                'priority_id' => 2,
                'problem' => 'Jaringan lambat di area kantor',
                'solution' => 'Analisis traffic dan restart switch utama',
                'request_date' => Carbon::now()->subDay(),
                'start_date' => Carbon::now()->subHours(20),
                'end_date' => Carbon::now()->subHours(10),
                'waiting_hour' => 4,
                'time_spent' => 150,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
