<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TicketsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tickets')->insert([
            [
                'ticket_code' => 'TCK-001',
                'user_id' => 1,
                'support_id' => 2,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 1,
                'priority_id' => 2,
                'problem' => 'Laptop tidak bisa menyala',
                'image' => 'tickets/laptop_mati.jpg',
                'solution' => 'Ganti adaptor charger dan cek kabel power.',
                'notes' => 'Perlu konfirmasi apakah charger baru sudah tersedia.',
                'request_date' => Carbon::now()->subDays(10),
                'waiting_hour' => 2,
                'start_date' => Carbon::now()->subDays(9),
                'end_date' => Carbon::now()->subDays(8),
                'time_spent' => 90,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-002',
                'user_id' => 2,
                'support_id' => 3,
                'problem_category_id' => 2,
                'assets_id' => 2,
                'status_id' => 2,
                'priority_id' => 3,
                'problem' => 'Printer tidak terdeteksi di jaringan',
                'image' => 'tickets/printer_error.jpg',
                'solution' => 'Reinstall driver dan setting ulang IP printer.',
                'notes' => 'Jaringan sempat unstable saat troubleshooting.',
                'request_date' => Carbon::now()->subDays(9),
                'waiting_hour' => 3,
                'start_date' => Carbon::now()->subDays(8),
                'end_date' => Carbon::now()->subDays(7),
                'time_spent' => 110,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-003',
                'user_id' => 3,
                'support_id' => 1,
                'problem_category_id' => 3,
                'assets_id' => 3,
                'status_id' => 3,
                'priority_id' => 1,
                'problem' => 'Sistem ERP tidak bisa login',
                'image' => 'tickets/erp_login_failed.png',
                'solution' => 'Reset session server dan clear cache database.',
                'notes' => 'Butuh pengujian ulang login multi-user.',
                'request_date' => Carbon::now()->subDays(8),
                'waiting_hour' => 1,
                'start_date' => Carbon::now()->subDays(7),
                'end_date' => Carbon::now()->subDays(6),
                'time_spent' => 75,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-004',
                'user_id' => 1,
                'support_id' => 3,
                'problem_category_id' => 1,
                'assets_id' => 2,
                'status_id' => 1,
                'priority_id' => 2,
                'problem' => 'Email tidak bisa terkirim',
                'image' => 'tickets/email_failed.jpg',
                'solution' => 'Cek konfigurasi SMTP dan clear cache Outlook.',
                'notes' => 'Perlu update password akun email.',
                'request_date' => Carbon::now()->subDays(7),
                'waiting_hour' => 4,
                'start_date' => Carbon::now()->subDays(6),
                'end_date' => Carbon::now()->subDays(5),
                'time_spent' => 100,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-005',
                'user_id' => 2,
                'support_id' => 1,
                'problem_category_id' => 1,
                'assets_id' => 1,
                'status_id' => 2,
                'priority_id' => 1,
                'problem' => 'Komputer sering restart sendiri',
                'image' => 'tickets/pc_restart.jpg',
                'solution' => 'Ganti PSU dan lakukan stress test RAM.',
                'notes' => 'Hardware rusak akibat overheat.',
                'request_date' => Carbon::now()->subDays(6),
                'waiting_hour' => 5,
                'start_date' => Carbon::now()->subDays(5),
                'end_date' => Carbon::now()->subDays(4),
                'time_spent' => 120,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-006',
                'user_id' => 3,
                'support_id' => 2,
                'problem_category_id' => 2,
                'assets_id' => 3,
                'status_id' => 3,
                'priority_id' => 3,
                'problem' => 'Aplikasi internal error 404',
                'image' => 'tickets/app_404.png',
                'solution' => 'Perbaiki routing dan redeploy aplikasi.',
                'notes' => 'Perlu push ulang ke server production.',
                'request_date' => Carbon::now()->subDays(5),
                'waiting_hour' => 2,
                'start_date' => Carbon::now()->subDays(4),
                'end_date' => Carbon::now()->subDays(3),
                'time_spent' => 130,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-007',
                'user_id' => 1,
                'support_id' => 1,
                'problem_category_id' => 1,
                'assets_id' => 2,
                'status_id' => 2,
                'priority_id' => 2,
                'problem' => 'Monitor tidak menampilkan gambar',
                'image' => 'tickets/monitor_black.jpg',
                'solution' => 'Ganti kabel HDMI dan uji monitor lain.',
                'notes' => 'Monitor rusak, perlu penggantian baru.',
                'request_date' => Carbon::now()->subDays(4),
                'waiting_hour' => 1,
                'start_date' => Carbon::now()->subDays(3),
                'end_date' => Carbon::now()->subDays(2),
                'time_spent' => 60,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-008',
                'user_id' => 2,
                'support_id' => 3,
                'problem_category_id' => 3,
                'assets_id' => 1,
                'status_id' => 1,
                'priority_id' => 1,
                'problem' => 'Access point tidak berfungsi',
                'image' => 'tickets/ap_down.png',
                'solution' => 'Reset access point dan update firmware.',
                'notes' => 'Firmware lama menyebabkan bug koneksi.',
                'request_date' => Carbon::now()->subDays(3),
                'waiting_hour' => 3,
                'start_date' => Carbon::now()->subDays(2),
                'end_date' => Carbon::now()->subDay(),
                'time_spent' => 140,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-009',
                'user_id' => 3,
                'support_id' => 2,
                'problem_category_id' => 2,
                'assets_id' => 3,
                'status_id' => 2,
                'priority_id' => 3,
                'problem' => 'Keyboard tidak berfungsi',
                'image' => 'tickets/keyboard_error.jpg',
                'solution' => 'Ganti keyboard baru dan tes port USB.',
                'notes' => 'Perangkat lama sudah rusak total.',
                'request_date' => Carbon::now()->subDays(2),
                'waiting_hour' => 2,
                'start_date' => Carbon::now()->subDay(),
                'end_date' => Carbon::now(),
                'time_spent' => 90,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'ticket_code' => 'TCK-010',
                'user_id' => 1,
                'support_id' => 2,
                'problem_category_id' => 3,
                'assets_id' => 1,
                'status_id' => 3,
                'priority_id' => 2,
                'problem' => 'Jaringan lambat di area kantor',
                'image' => 'tickets/network_slow.jpg',
                'solution' => 'Analisis traffic dan restart switch utama.',
                'notes' => 'Disarankan upgrade bandwidth kantor.',
                'request_date' => Carbon::now()->subDay(),
                'waiting_hour' => 4,
                'start_date' => Carbon::now()->subhour(20),
                'end_date' => Carbon::now()->subhour(10),
                'time_spent' => 150,
                'is_late' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
